# fly.toml app configuration file generated for uniswap-loader on 2023-09-16T06:24:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hyperliquid-loader"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
