create table public.rightmove_property_listing_event_log
( 
    event_id                                 bigint  not null primary key,
    delivery_id                              bigint  not null,
    event_type                               text    not null,


    curr_id                                  bigint,
    curr_bedrooms                            integer,
    curr_bathrooms                           integer,
    curr_number_of_images                    integer,
    curr_summary                             text,
    curr_display_address                     varchar(255),
    curr_postcode_area                       varchar(255),
    curr_country_code                        char(2),
    curr_latitude                            numeric(10, 6),
    curr_longitude                           numeric(10, 6),
    curr_property_images                     text,
    curr_property_sub_type                   varchar(255),
    curr_listing_update_reason               varchar(255),
    curr_listing_update_date                 timestamp with time zone,
    curr_price_amount                        integer,
    curr_price_frequency                     varchar(50),
    curr_currency_code                       char(3),
    curr_display_price                       text,
    curr_display_price_qualifier             varchar(255),
    curr_branch_id                           integer,
    curr_branch_display_name                 varchar(255),
    curr_branch_name                         varchar(255),
    curr_branch_landing_page_url             text,
    curr_development                         boolean,
    curr_commercial                          boolean,
    curr_transaction_type                    varchar(50),
    curr_product_label_text                  varchar(255),
    curr_spotlight_label                     boolean,
    curr_residential                         boolean,
    curr_students                            boolean,
    curr_auction                             boolean,
    curr_fees_apply                          boolean,
    curr_fees_apply_text                     text,
    curr_display_size                        varchar(255),
    curr_property_url                        text,
    curr_channel                             varchar(50),
    curr_listing_date                        timestamp with time zone,
    curr_added_or_reduced                    varchar(255),
    curr_property_type_full_description      text,
    curr_hash                                text,


    prev_event_id                            text,
    prev_delivery_id                         text,
    prev_id                                  bigint,
    prev_bedrooms                            integer,
    prev_bathrooms                           integer,
    prev_number_of_images                    integer,
    prev_summary                             text,
    prev_display_address                     varchar(255),
    prev_postcode_area                       varchar(255),
    prev_country_code                        char(2),
    prev_latitude                            numeric(10, 6),
    prev_longitude                           numeric(10, 6),
    prev_property_images                     text,
    prev_property_sub_type                   varchar(255),
    prev_listing_update_reason               varchar(255),
    prev_listing_update_date                 timestamp with time zone,
    prev_price_amount                        integer,
    prev_price_frequency                     varchar(50),
    prev_currency_code                       char(3),
    prev_display_price                       text,
    prev_display_price_qualifier             varchar(255),
    prev_branch_id                           integer,
    prev_branch_display_name                 varchar(255),
    prev_branch_name                         varchar(255),
    prev_branch_landing_page_url             text,
    prev_development                         boolean,
    prev_commercial                          boolean,
    prev_transaction_type                    varchar(50),
    prev_product_label_text                  varchar(255),
    prev_spotlight_label                     boolean,
    prev_residential                         boolean,
    prev_students                            boolean,
    prev_auction                             boolean,
    prev_fees_apply                          boolean,
    prev_fees_apply_text                     text,
    prev_display_size                        varchar(255),
    prev_property_url                        text,
    prev_channel                             varchar(50),
    prev_listing_date                        timestamp with time zone,
    prev_added_or_reduced                    varchar(255),
    prev_property_type_full_description      text,
    prev_hash                                text,
   
    mask                                     varchar not null
);