create table public.rightmove_property_listings_raw
(
    id                             bigint not null
        primary key,
    bedrooms                       integer,
    bathrooms                      integer,
    number_of_images               integer,
    summary                        text,
    display_address                varchar(255),
    postcode_area                  varchar(255),
    property_url                   text,  
    country_code                   char(2),
    latitude                       numeric(10, 6),
    longitude                      numeric(10, 6),
    property_images                text,
    property_sub_type              varchar(255),
    listing_update_reason          varchar(255),
    listing_update_date            timestamp with time zone,
    price_amount                   integer,
    price_frequency                varchar(50),
    currency_code                  char(3),
    display_price                  text,
    display_price_qualifier        varchar(255),
    branch_id                      integer,
    branch_display_name            varchar(255),
    branch_name                    varchar(255),
    branch_landing_page_url        text,
    development                    boolean,
    commercial                     boolean,
    transaction_type               varchar(50),
    product_label_text             varchar(255),
    spotlight_label                boolean,
    residential                    boolean,
    students                       boolean,
    auction                        boolean,
    fees_apply                     boolean,
    fees_apply_text                text,
    display_size                   varchar(255),
    property_url                   text,
    channel                        varchar(50),
    listing_date                   timestamp with time zone,
    added_or_reduced               varchar(255),
    property_type_full_description text
);
